version: '3.8'
name: dcms
services:
  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    command: sh -c "yarn install && yarn run dev"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

  auth:
    image: nguyenthaidien/keycloak:latest
    working_dir: /auth
    volumes:
      - ./auth:/auth
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
  eureka-server:
    image: nguyenthaidien/eurekaserver:latest
    ports:
      - "8761:8761"
    environment:
      EUREKA_SERVER_PORT: 8761
      EUREKA_SERVER_HOSTNAME: eureka-server
  fespa:
    image: nguyenthaidien/fespa:latest
    ports:
      - "8081:8081"
    environment:
      FESPA_SERVER_PORT: 443
      FESPA_SERVER_HOSTNAME: fespa
